### ISSUE TITLE
Postgresql merge error

### ISSUE THREAD

**Issue by mhcpan** [freewillfx-azenqos/azm_db_merge#1]
Hi,
Error at merging azm to postgresql db.  

Instead of 

`"ALTER TABLE "events" ADD  "log_hash" BIGINT,  "geom" bytea;"`

I think it should be
`
ALTER TABLE "events" ADD COLUMN "log_hash" BIGINT, ADD COLUMN "geom" bytea;`

p.s. 
1. Brand new table create seems fine, it is adding additional columns that has problem.
2. bytea is not a geometry type. With Postgis, it should be  geometry(Point, 4326 ) where 4326 is the SRID.
```
azm_db_merge version 1.0 Copyright (c) 2016 Freewill FX Co., Ltd. All rights reserved.
### get module:  gen_sql_handler
module dir: ['SQL_MAX_TABLE_NAME_LEN', '__builtins__', '__doc__', '__file__', '__name__', '__package__', 'azm_db_constants', 'call', 'check_if_already_merged', 'close', 'commit', 'connect', 'create', 'dprint', 'g_bulk_insert_mode', 'g_conn', 'g_cursor', 'g_dir_processing_azm', 'g_exec_buf', 'g_is_ms', 'g_is_postgre', 'g_prev_create_statement_column_names', 'g_prev_create_statement_table_name', 'g_unmerge_logs_row', 'get_col_names', 'get_remote_columns', 'get_table_name', 'os', 'pyodbc', 'sql_adj_line']
supplied azm_file is a directory - get a list of .azm files to process:
n_azm_files to process: 1
list of azm files to process: ['../logs/359600060377748 4_1_2017 13.8.3.azm']
## START process azm 1/1: '../logs/359600060377748 4_1_2017 13.8.3.azm'
args['azm_file']: ../logs/359600060377748 4_1_2017 13.8.3.azm
azm_fp: /home/radio/Azenqoslog/logs/359600060377748 4_1_2017 13.8.3.azm
dir_azm: /home/radio/Azenqoslog/logs
azm_name_no_ext: 359600060377748 4_1_2017 13.8.3
using live in-memory pipe of sqlite3 dump output parse mode
starting sqlite3 subporcess...
### connecting to dbms...
PostgreSQL mode initializing...
mssql_handler close() - cleanup()
Connecting... Target DBMS type: PostgreSQL
using connect_str: dbname=azqdb user=azqdbuser password=XXXXXX
connected
checking if this log has already been imported/merged: 359600060377748 4_1_2017 13.8.3.azm
This log hasn't been imported into target db yet - ok to proceed
is this table in --omit_tables ? android_metadata = False
is this table in --omit_tables ? events = False

processing: create/alter/insert for table_name: events
processing create at handler module...
n_cols_to_add: 2 - need to alter table - add cols:[' "log_hash" BIGINT', ' "geom" bytea']
remote_cols:
[['imei_id', ''], ['time', ''], ['time_ms', ''], ['posid', ''], ['seqid', ''], ['netid', ''], ['event_id', ''], ['name', ''], ['info', ''], ['detail', '']]
execute alter_str: ALTER TABLE "events" ADD  "log_hash" BIGINT,  "geom" bytea;
re-raise exception e -  ['Traceback (most recent call last):\n', '  File "azm_db_merge.py", line 495, in process_azm_file\n    handle_sql3_dump_line(args, line)\n', '  File "azm_db_merge.py", line 266, in handle_sql3_dump_line\n    handle_ret = g_create_function(args, line)\n', '  File "/home/radio/Azenqoslog/azm_db_merge-master/gen_sql_handler.py", line 387, in create\n    ret = g_cursor.execute(sqlstr)\n', 'ProgrammingError: syntax error at or near ""geom""\nLINE 1: ALTER TABLE "events" ADD  "log_hash" BIGINT,  "geom" bytea;\n                                                      ^\n\n']
cleanup start...
mssql_handler close() - cleanup()
cleanup_tmp_dir...
## FAILED: process azm ../logs/359600060377748 4_1_2017 13.8.3.azm failed with below exception:
(start of exception)
syntax error at or near ""geom""
LINE 1: ALTER TABLE "events" ADD  "log_hash" BIGINT,  "geom" bytea;
                                                      ^

['Traceback (most recent call last):\n', '  File "azm_db_merge.py", line 601, in <module>\n    ret = process_azm_file(args)\n', '  File "azm_db_merge.py", line 521, in process_azm_file\n    raise e\n', 'ProgrammingError: syntax error at or near ""geom""\nLINE 1: ALTER TABLE "events" ADD  "log_hash" BIGINT,  "geom" bytea;\n                                                      ^\n\n'](end of exception)
--folder_mode_stop_on_first_failure specified - exit now.
```

**Comment by ykasidit** [comment]
Thanks very much Mike! This issue has been fixed in today's commits.
